extends:
  - eslint:recommended
  - plugin:prettier/recommended

env:
  browser: false
  es2020: true
  node: true

rules:
  # Allow an escape hatch for unused arguments.
  no-unused-vars:
    - error
    - argsIgnorePattern: "^_(ignored|unused)(_[a-z0-9]+)?"
